#!/usr/bin/env python3
"""Shared humanize utilities for documentation markdown passes."""
from __future__ import annotations

import re

WORD_REPLACEMENTS: list[tuple[str, str]] = [
    (r"\bAdditionally\b", "Also"),
    (r"\bAdditionally,\b", "Also,"),
    (r"\bFurthermore\b", "And"),
    (r"\bFurthermore,\b", "And,"),
    (r"\bMoreover\b", "On top of that"),
    (r"\bMoreover,\b", "On top of that,"),
    (r"\bSubsequently\b", "After that"),
    (r"\bAccordingly\b", "So"),
    (r"\bAccordingly,\b", "So,"),
    (r"\bThus\b", "So"),
    (r"\bThus,\b", "So,"),
    (r"\bHence\b", "That's why"),
    (r"\bHence,\b", "That's why,"),
    (r"\bConsequently\b", "As a result"),
    (r"\bConsequently,\b", "As a result,"),
    (r"\bdelve into\b", "look into"),
    (r"\bdelve\b", "look into"),
    (r"\bunderscores\b", "shows"),
    (r"\bunderscore\b", "show"),
    (r"\bUnderscore\b", "Show"),
    (r"\bpivotal\b", "central"),
    (r"\bPivotal\b", "Central"),
    (r"\brobust\b", "reliable"),
    (r"\bRobust\b", "Reliable"),
    (r"\bseamless\b", "smooth"),
    (r"\bSeamless\b", "Smooth"),
    (r"\bcomprehensive\b", "full"),
    (r"\bComprehensive\b", "Full"),
    (r"\bholistic\b", "full-picture"),
    (r"\bHolistic\b", "Full-picture"),
    (r"\bnuanced\b", "subtle"),
    (r"\bNuanced\b", "Subtle"),
    (r"\bleverage\b", "use"),
    (r"\bLeverage\b", "Use"),
    (r"\bleveraging\b", "using"),
    (r"\bLeveraging\b", "Using"),
    (r"\butilize\b", "use"),
    (r"\bUtilize\b", "Use"),
    (r"\butilizing\b", "using"),
    (r"\bfacilitate\b", "help"),
    (r"\bFacilitate\b", "Help"),
    (r"\bstreamline\b", "simplify"),
    (r"\bStreamline\b", "Simplify"),
    (r"\bproactive\b", "ahead-of-time"),
    (r"\bProactive\b", "Ahead-of-time"),
    (r"\bsynergy\b", "combined effect"),
    (r"\bparadigm\b", "model"),
    (r"\bParadigm\b", "Model"),
    (r"\becosystem\b", "network"),
    (r"\bEcosystem\b", "Network"),
    (r"\blandscape\b", "field"),
    (r"\bLandscape\b", "Field"),
    (r"\brealm\b", "area"),
    (r"\bRealm\b", "Area"),
    (r"\bcornerstone\b", "foundation"),
    (r"\bCornerstone\b", "Foundation"),
    (r"\bgranular\b", "detailed"),
    (r"\bGranular\b", "Detailed"),
    (r"\bactionable\b", "concrete"),
    (r"\bActionable\b", "Concrete"),
    (r"\bkey takeaways\b", "what this means"),
    (r"\bKey takeaways\b", "What this means"),
    (r"\bcutting-edge\b", "current"),
    (r"\bstate-of-the-art\b", "current"),
    (r"\bbest practices\b", "common practice"),
    (r"\bBest practices\b", "Common practice"),
    (r"\bmoving forward\b", "from now on"),
    (r"\bgoing forward\b", "from now on"),
    (r"\bunpack\b", "explain"),
    (r"\bUnpack\b", "Explain"),
    (r"\bharness\b", "use"),
    (r"\bHarness\b", "Use"),
    (r"\bunlock\b", "open up"),
    (r"\bUnlock\b", "Open up"),
    (r"\bunleash\b", "release"),
    (r"\bsupercharge\b", "speed up"),
    (r"\bturbocharge\b", "speed up"),
    (r"\bcraft\b", "build"),
    (r"\bCraft\b", "Build"),
    (r"\belevate\b", "raise"),
    (r"\bfoster\b", "build"),
    (r"\bFoster\b", "Build"),
    (r"\bparamount\b", "most important"),
    (r"\bcrucial\b", "important"),
    (r"\bCrucial\b", "Important"),
    (r"\bessential\b", "necessary"),
    (r"\bEssential\b", "Necessary"),
    (r"\bvital\b", "necessary"),
    (r"\bVital\b", "Necessary"),
    (r"\bboasts\b", "has"),
    (r"\bshowcases\b", "shows"),
    (r"\bstands as\b", "is"),
    (r"\bserves as\b", "works as"),
    (r"\btestament\b", "proof"),
    (r"\btapestry\b", "mix"),
    (r"\binterplay\b", "interaction"),
    (r"\bintricate\b", "complex"),
    (r"\bmeticulous\b", "careful"),
    (r"\bvibrant\b", "active"),
    (r"\brenowned\b", "well-known"),
    (r"\bdiverse array\b", "range"),
    (r"\bin order to\b", "to"),
    (r"\bDue to the fact that\b", "Because"),
    (r"\bdue to the fact that\b", "because"),
    (r"\bIn the event that\b", "If"),
    (r"\bin the event that\b", "if"),
    (r"\bAt this point in time\b", "Now"),
    (r"\bat this point in time\b", "now"),
    (r"\bFor the purpose of\b", "To"),
    (r"\bfor the purpose of\b", "to"),
    (r"\bIt\'s worth noting that\b", ""),
    (r"\bIt is worth noting that\b", ""),
    (r"\bIt\'s worth noting\b", ""),
    (r"\bIt is worth noting\b", ""),
    (r"\bIt\'s important to note that\b", ""),
    (r"\bIt is important to note that\b", ""),
    (r"\bIt\'s important to note\b", ""),
    (r"\bIt is important to note\b", ""),
    (r"\bIn today\'s digital landscape\b", ""),
    (r"\bIn today\'s world\b", ""),
    (r"\bdeep dive\b", "detailed look"),
    (r"\bDeep dive\b", "Detailed look"),
    (r"\bdeep-dive\b", "detailed"),
    (r"\bDeep-dive\b", "Detailed"),
    (r"\bLet\'s explore\b", ""),
    (r"\bWe\'ll dive into\b", ""),
    (r"\bWithout further ado\b", ""),
    (r"\bNeedless to say,\b", ""),
    (r"\bneedless to say,\b", ""),
    (r"\bAt the end of the day,\b", ""),
    (r"\bat the end of the day,\b", ""),
    (r"\bFirst and foremost,\b", "First,"),
    (r"\bfirst and foremost,\b", "First,"),
    (r"\bLast but not least,\b", "Finally,"),
    (r"\blast but not least,\b", "Finally,"),
    (r"\bGenerally speaking,\b", ""),
    (r"\bBroadly speaking,\b", ""),
    (r"\bAs mentioned earlier,\b", ""),
    (r"\bas mentioned earlier,\b", ""),
    (r"\bAs noted above,\b", ""),
    (r"\bas noted above,\b", ""),
    (r"\bIndeed,\b", ""),
    (r"\bIndeed\b", ""),
    (r"\bCertainly,\b", ""),
    (r"\bOf course,\b", ""),
    (r"\bRest assured,\b", ""),
    (r"\bSimply put,\b", ""),
    (r"\bTo put it simply,\b", ""),
    (r"\bIn layman\'s terms,\b", ""),
    (r"\bIn essence,\b", ""),
    (r"\bAt its core,\b", ""),
    (r"\bNotably,\b", ""),
    (r"\bImportantly,\b", ""),
    (r"\bEssentially,\b", ""),
    (r"\bnavigate the complexities of\b", "work through"),
    (r"\bNavigate the complexities of\b", "Work through"),
    (r"\bnavigate complexity\b", "work through complexity"),
    (r"\bHarness the power of\b", "Use"),
    (r"\bharness the power of\b", "use"),
    (r"\bUnlock the potential of\b", "Use"),
    (r"\bunlock the potential of\b", "use"),
    (r"\bBridging the gap between\b", "Connecting"),
    (r"\bbridging the gap between\b", "connecting"),
    (r"\bLay the groundwork for\b", "Prepare for"),
    (r"\blay the groundwork for\b", "prepare for"),
    (r"\bFoster a culture of\b", "Build a habit of"),
    (r"\bfoster a culture of\b", "build a habit of"),
    (r"\bAt the forefront of\b", "Leading"),
    (r"\bat the forefront of\b", "leading"),
    (r"\bplays a crucial role in\b", "matters for"),
    (r"\bplays a pivotal role in\b", "matters for"),
    (r"\bplays a vital role in\b", "matters for"),
    (r"\bplays an important role in\b", "matters for"),
    (r"\benterprise-grade\b", ""),
    (r"\bbest-in-class\b", ""),
    (r"\bworld-class\b", ""),
    (r"\bindustry-leading\b", ""),
    (r"\bunprecedented\b", "unusual"),
    (r"\bUnprecedented\b", "Unusual"),
    (r"\bsophisticated\b", "complex"),
    (r"\bSophisticated\b", "Complex"),
    (r"\bpowerful\b", ""),
    (r"\bPowerful\b", ""),
]


def clean_front_matter(text: str) -> str:
    if not text.startswith("---"):
        return text
    end = text.find("---", 3)
    if end == -1:
        return text
    fm = text[3:end].strip().splitlines()
    body = text[end + 3 :]
    kept = []
    for line in fm:
        if line.strip().startswith("audience:"):
            continue
        kept.append(line)
    if not kept:
        return text.lstrip("---").lstrip()
    return "---\n" + "\n".join(kept) + "\n---" + body


def humanize(text: str) -> str:
    text = clean_front_matter(text)
    text = re.sub(r"^####\s*❓\s*", "#### ", text, flags=re.MULTILINE)
    text = re.sub(r"^###\s*❓\s*", "### ", text, flags=re.MULTILINE)
    for pat, repl in WORD_REPLACEMENTS:
        text = re.sub(pat, repl, text)
    text = re.sub(r"^[ \t]+,", "", text, flags=re.MULTILINE)
    text = re.sub(r"\.\s+\.", ".", text)
    return text
